In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#read the data set 
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
#print the data set 
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
#converting categorical data to numerical data
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
#Removing the unwanted cloumns from table
dataset=dataset.drop("User ID",axis=1)

In [6]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [7]:
#input and output Split form data 
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [9]:
#standardize the value using StandardScaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
#create a model of RandomforestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy','log_loss'],
              'max_features': ['auto','sqrt','log2'],'class_weight':['balanced','balanced_subsample'],
              'n_estimators':[10,100]} 
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   # fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Anconda\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
60 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anconda\lib\site-packages\sklearn\ensemble\_forest.py", line 450, in fit
    trees = Parallel(
  File "C:\Anconda\lib\site-packages\joblib\parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Anconda\lib\site-packages\joblib\parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Anconda\lib\site-packages\joblib\parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Anconda\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Anconda\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Anconda\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Anconda\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Anconda\lib\site-packages\sklearn\utils\fixes.py", line 216, in __call__
    return self.function(*args, **kwargs)
  File "C:\Anconda\lib\site-packages\sklearn\ensemble\_forest.py", line 185, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Anconda\lib\site-packages\sklearn\tree\_classes.py", line 937, in fit
    super().fit(
  File "C:\Anconda\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anconda\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [0.79322004 0.83598246 0.80855079 0.86573742 0.81787191 0.83607726
 0.82709049 0.87240409 0.82165822 0.86137845 0.83243845 0.84039574
        nan        nan        nan        nan        nan        nan
 0.81825972 0.85431962 0.82783626 0.86160787 0.83710766 0.86573742
 0.83620368 0.8597995  0.83024012 0.84039574 0.81537932 0.85184764
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'class_weight': ['balanced', 'balanced_subsample'],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [13]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
print(cm)
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
print(clf_report)

[[79  6]
 [ 4 45]]
              precision    recall  f1-score   support

           0       0.95      0.93      0.94        85
           1       0.88      0.92      0.90        49

    accuracy                           0.93       134
   macro avg       0.92      0.92      0.92       134
weighted avg       0.93      0.93      0.93       134

In [14]:
#Calculate the F1Score 
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'auto', 'n_estimators': 100}: 0.9256751954513147

In [ ]:
#calculate the roc_auc_score 
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

In [15]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.030056,0.012293,0.006197,0.007596,balanced,gini,auto,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.687500,0.742857,0.780488,0.810811,0.944444,0.793220,0.086085,24
1,0.326304,0.039380,0.019125,0.002249,balanced,gini,auto,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.764706,0.810811,0.809524,0.871795,0.923077,0.835982,0.055285,14
2,0.034692,0.012342,0.015936,0.017868,balanced,gini,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.666667,0.842105,0.809524,0.842105,0.882353,0.808551,0.074606,23
3,0.351641,0.006522,0.019818,0.005367,balanced,gini,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.800000,0.871795,0.809524,0.900000,0.947368,0.865737,0.055418,2
4,0.030256,0.007968,0.006244,0.004172,balanced,gini,log2,10,"{'class_weight': 'balanced', 'criterion': 'gin...",0.727273,0.756757,0.829268,0.857143,0.918919,0.817872,0.069030,21
5,0.462596,0.138211,0.069779,0.038622,balanced,gini,log2,100,"{'class_weight': 'balanced', 'criterion': 'gin...",0.727273,0.820513,0.809524,0.900000,0.923077,0.836077,0.069915,13
6,0.034661,0.004782,0.007346,0.004991,balanced,entropy,auto,10,"{'class_weight': 'balanced', 'criterion': 'ent...",0.727273,0.789474,0.809524,0.926829,0.882353,0.827090,0.070269,18
7,0.453062,0.067610,0.021972,0.005981,balanced,entropy,auto,100,"{'class_weight': 'balanced', 'criterion': 'ent...",0.833333,0.871795,0.809524,0.900000,0.947368,0.872404,0.048707,1
8,0.031604,0.001396,0.004743,0.006279,balanced,entropy,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'ent...",0.727273,0.810811,0.809524,0.871795,0.888889,0.821658,0.056934,19
9,0.476646,0.032811,0.056639,0.027893,balanced,entropy,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'ent...",0.800000,0.850000,0.809524,0.900000,0.947368,0.861378,0.055627,5
10,0.036285,0.006699,0.016148,0.019777,balanced,entropy,log2,10,"{'class_weight': 'balanced', 'criterion': 'ent...",0.800000,0.810811,0.790698,0.871795,0.888889,0.832438,0.039995,15
11,0.471975,0.090839,0.040288,0.012988,balanced,entropy,log2,100,"{'class_weight': 'balanced', 'criterion': 'ent...",0.727273,0.842105,0.809524,0.900000,0.923077,0.840396,0.069486,9
12,0.010222,0.005757,0.000000,0.000000,balanced,log_loss,auto,10,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,34
13,0.125587,0.040961,0.000000,0.000000,balanced,log_loss,auto,100,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,33
14,0.011369,0.006321,0.000000,0.000000,balanced,log_loss,sqrt,10,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,32
15,0.136567,0.058153,0.000000,0.000000,balanced,log_loss,sqrt,100,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
16,0.013386,0.010289,0.000000,0.000000,balanced,log_loss,log2,10,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,30
17,0.112422,0.023440,0.000000,0.000000,balanced,log_loss,log2,100,"{'class_weight': 'balanced', 'criterion': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,29
18,0.105757,0.051823,0.003861,0.005063,balanced_subsample,gini,auto,10,"{'class_weight': 'balanced_subsample', 'criter...",0.833333,0.777778,0.780488,0.810811,0.888889,0.818260,0.040833,20
19,0.547678,0.103820,0.059631,0.059893,balanced_subsample,gini,auto,100,"{'class_weight': 'balanced_subsample', 'criter...",0.764706,0.850000,0.809524,0.900000,0.947368,0.854320,0.064499,7
20,0.040859,0.017181,0.003857,0.006036,balanced_subsample,gini,sqrt,10,"{'class_weight': 'balanced_subsample', 'criter...",0.800000,0.777778,0.809524,0.894737,0.857143,0.827836,0.042310,17
21,0.773193,0.449735,0.067446,0.059750,balanced_subsample,gini,sqrt,100,"{'class_weight': 'balanced_subsample', 'criter...",0.833333,0.842105,0.809524,0.900000,0.923077,0.861608,0.042767,4
22,0.056114,0.037888,0.009396,0.012534,balanced_subsample,gini,log2,10,"{'class_weight': 'balanced_subsample', 'criter...",0.727273,0.833333,0.780488,0.900000,0.944444,0.837108,0.078435,11
23,0.863997,0.317211,0.059571,0.080105,balanced_subsample,gini,log2,100,"{'class_weight': 'balanced_subsample', 'criter...",0.800000,0.871795,0.809524,0.900000,0.947368,0.865737,0.055418,2
24,0.053747,0.027127,0.001202,0.002405,balanced_subsample,entropy,auto,10,"{'class_weight': 'balanced_subsample', 'criter...",0.800000,0.810811,0.809524,0.871795,0.888889,0.836204,0.036633,12
25,1.070183,0.123989,0.050206,0.043727,balanced_subsample,entropy,auto,100,"{'class_weight': 'balanced_subsample', 'criter...",0.800000,0.842105,0.809524,0.900000,0.947368,0.859799,0.056038,6
26,0.102486,0.064032,0.006254,0.007660,balanced_subsample,entropy,sqrt,10,"{'class_weight': 'balanced_subsample', 'criter...",0.833333,0.777778,0.780488,0.864865,0.894737,0.830240,0.046034,16
27,1.122923,0.138871,0.076492,0.073642,balanced_subsample,entropy,sqrt,100,"{'class_weight': 'balanced_subsample', 'criter...",0.727273,0.842105,0.809524,0.900000,0.923077,0.840396,0.069486,9
28,0.095333,0.044706,0.003125,0.006250,balanced_subsample,entropy,log2,10,"{'class_weight': 'balanced_subsample', 'criter...",0.764706,0.777778,0.769231,0.842105,0.923077,0.815379,0.060703,22
29,1.014883,0.233944,0.015626,0.013976,balanced_subsample,entropy,log2,100,"{'class_weight': 'balanced_subsample', 'criter...",0.764706,0.810811,0.809524,0.926829,0.947368,0.851848,0.071855,8
30,0.048495,0.037906,0.000000,0.000000,balanced_subsample,log_loss,auto,10,"{'class_weight': 'balanced_subsample', 'criter...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,27
31,0.118072,0.066931,0.000000,0.000000,balanced_subsample,log_loss,auto,100,"{'class_weight': 'balanced_subsample', 'criter...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
32,0.018436,0.011796,0.000000,0.000000,balanced_subsample,log_loss,sqrt,10,"{'class_weight': 'balanced_subsample', 'criter...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,28
33,0.187640,0.054166,0.000000,0.000000,balanced_subsample,log_loss,sqrt,100,"{'class_weight': 'balanced_subsample', 'criter...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
34,0.046905,0.052335,0.000000,0.000000,balanced_subsample,log_loss,log2,10,"{'class_weight': 'balanced_subsample', 'criter...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,35
35,0.156271,0.027933,0.000000,0.000000,balanced_subsample,log_loss,log2,100,"{'class_weight': 'balanced_subsample', 'criter...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,36

In [16]:
Age_input=float(input("Age:"))
EstimatedSalary_input=float(input("EstimatedSalary:"))
Gender_Male_input=float(input("Gender_Male:"))

Age:25
EstimatedSalary:15000
Gender_Male:1

In [17]:
Purchase_Prediction=grid.predict([[Age_input,EstimatedSalary_input,Gender_Male_input]])
print("Purchase_Prediction={}".format(Purchase_Prediction))

Purchase_Prediction=[1]